# Builds a library, and packages it up.
#
# Works on a release/version tag
#   e.g release/1.0.2 will build v1.0.2
#

name: Build and Package

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NAME: Our.Umbraco.Honeypot
  OUTPUT: ./Output
  LIBRARY_FOLDER: ./src/Our.Umbraco.Honeypot
  CONFIG: release

on:
  push:
    tags:
      - "release/*"

jobs:
  build:
    runs-on: windows-latest

    steps:      
      - name: Get Version 
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/release\//}
        shell: bash
      
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.7        
        
      - name: Setup .net core
        uses: actions/setup-dotnet@v2.0.1
      
      - name: Create Our.Umbraco.Honeypot.Core
        run: dotnet pack ./src/Our.Umbraco.Honeypot.Core -c ${{ env.CONFIG }} -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }} 
      
      - name: Create Our.Umbraco.Honeypot
        run: dotnet pack ./src/Our.Umbraco.Honeypot -c ${{ env.CONFIG }} -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }} 
      
      - name: Create Our.Umbraco.Honeypot.V8
        run: dotnet pack ./src/Our.Umbraco.Honeypot.V8 -c ${{ env.CONFIG }} -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }} 
     
      - name: Push Our.Umbraco.Honeypot.Core
        run: dotnet nuget push ${{ env.OUTPUT }}/Our.Umbraco.Honeypot.Core.${{ steps.get_version.outputs.VERSION }}.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      
      - name: Push Our.Umbraco.Honeypot
        run: dotnet nuget push ${{ env.OUTPUT }}/Our.Umbraco.Honeypot.${{ steps.get_version.outputs.VERSION }}.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
      - name: Push Our.Umbraco.Honeypot.V8
        run: dotnet nuget push ${{ env.OUTPUT }}/Our.Umbraco.Honeypot.V8.${{ steps.get_version.outputs.VERSION }}.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-Results-${{ steps.get_version.outputs.VERSION }}
          path: ${{ env.OUTPUT }}/**/*